/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MainPage: typeof import('./components/MainPage.vue')['default']
    NotFound: typeof import('./components/NotFound.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    ProductDetails: typeof import('./components/ProductDetails.vue')['default']
    RedirectButton: typeof import('./components/RedirectButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/SearchInput.vue')['default']
    WelcomePage: typeof import('./components/WelcomePage.vue')['default']
  }
}
